[book]
authors = ["chenxiaolong"]
language = "en"
src = "src"
title = "光线追踪"

[output.html]
additional-css = ["./theme/css/catppuccin.css", "./theme/css/custom.css"]
default-theme = "latte"
preferred-dark-theme = "latte"

[preprocessor.katex]
after = ["links"]